[package]
authors = ["Patrick Carroll <patrick@patrickomatic.com>"]
description = "Compile csvpp source code to a target spreadsheet format"
homepage = "https://github.com/patrickomatic/csv-plus-plus"
keywords = ["csv++", "csvpp", "csv", "spreadsheet"]
license = "MIT"
name = "csvpp"
repository = "https://github.com/patrickomatic/csv-plus-plus"
version = "0.4.0"
edition = "2021"

[dependencies]
a1_notation = "0.4.2"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.2.7", features = ["derive"] }
colored = "^2.0"
csv = "1"
google-drive3 = "^5.0"
google-sheets4 = "^5.0"
home = "^0.5"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "^1.0", features = ["rt"] }
# umya-spreadsheet = "^1.0.3"
umya-spreadsheet = { git = "https://github.com/MathNya/umya-spreadsheet.git", rev = "878d549" }
# umya-spreadsheet = { path = "../umya-spreadsheet" }

[dev-dependencies]
cross = "^0.2"
rand = "^0.8"

[profile.release]
strip = "debuginfo"

[profile.test]
# disable coloring of output in tests (makes it easier to diff)
dumb_terminal = ["colored/no-color"]
