[package]
description = "Compile csvpp source code to a target spreadsheet format"
name = "csvpp"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
clap = { version = "4.2.7", features = ["derive"] }
csv = "1"
lazy_static = "1"
regex = "1"
