name: csv++

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: rustup component add rustfmt clippy

    - name: Build
      run: cargo build

    - name: Lint (clippy)
      run: cargo clippy -- -D warnings

    - name: Lint (rustfmt)
      run: cargo fmt --all -- --check

    - name: Tests
      run: cargo test

    # - name: Code Coverage
    # uses: actions-rs/grcov@v0.1.5
